"""add suppliers, purchases, purchase_items, returns

Revision ID: a4750b4a1a2a
Revises: 833f20648fab
Create Date: 2026-07-25 15:22:04.132959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4750b4a1a2a'
down_revision: Union[str, Sequence[str], None] = '833f20648fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchases_purchase_date', 'purchases', ['purchase_date'], unique=False)
    op.create_index('ix_purchases_supplier_id', 'purchases', ['supplier_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_items_qty_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_items_medicine_id', 'purchase_items', ['medicine_id'], unique=False)
    op.create_index('ix_purchase_items_purchase_id', 'purchase_items', ['purchase_id'], unique=False)
    op.create_table('returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_type', sa.String(length=10), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('returned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(return_type = 'sales' AND sale_id IS NOT NULL AND supplier_id IS NULL) OR (return_type = 'purchase' AND supplier_id IS NOT NULL AND sale_id IS NULL)", name='ck_returns_type_fk_consistency'),
    sa.CheckConstraint("return_type IN ('sales', 'purchase')", name='ck_returns_type_valid'),
    sa.CheckConstraint('quantity > 0', name='ck_returns_qty_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_returns_medicine_id', 'returns', ['medicine_id'], unique=False)
    op.create_index('ix_returns_return_type', 'returns', ['return_type'], unique=False)
    op.create_index('ix_returns_returned_at', 'returns', ['returned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_returns_returned_at', table_name='returns')
    op.drop_index('ix_returns_return_type', table_name='returns')
    op.drop_index('ix_returns_medicine_id', table_name='returns')
    op.drop_table('returns')
    op.drop_index('ix_purchase_items_purchase_id', table_name='purchase_items')
    op.drop_index('ix_purchase_items_medicine_id', table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('ix_purchases_supplier_id', table_name='purchases')
    op.drop_index('ix_purchases_purchase_date', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
