"""Pydantic schemas for the Business Planner."""

from pydantic import BaseModel, Field


class PlannerOutput(BaseModel):
    """Structured plan generated by the Business Planner."""

    tasks: list[str] = Field(
        ...,
        description=(
            "List of business capabilities required to answer "
            "the user's question."
        ),
    )